name: widget-server pipe

on:
  push:
    branches:
      - 'main'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-push-image
        run: |
          docker build -t widget-server:v3
          docker tag widget-server:v3 438930004785.dkr.ecr.us-east-2.amazonaws.com/ftr-rocketseat/widget-server:v3
          docker push 438930004785.dkr.ecr.us-east-2.amazonaws.com/ftr-rocketseat/widget-server:v3